MyHealthClinic/Controllers/AvailableTimesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using MyHealthClinic.Models;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using System;

namespace MyHealthClinic.Controllers
{
    public class AvailableTimesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set { _userManager = value; }
        }

        // GET: AvailableTimes/id?
        public ActionResult Index(string id)
        {
            var model = db.AvailableTimes
                .Where(at => DateTime.Compare(at.StartTime, DateTime.Now) > 0)
                .Include(at => at.GeneralPractioner)
                .ToList();
            if (id != null)
            {
                model = db.AvailableTimes
                    .Where(at => at.GeneralPractioner.Id == id)
                    .Where(at => DateTime.Compare(at.StartTime, DateTime.Now) > 0)
                    .Include(at => at.GeneralPractioner)
                    .ToList();
            }
            return View(model);
        }

        // GET: AvailableTimes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AvailableTime availableTime = db.AvailableTimes.Find(id);
            if (availableTime == null)
            {
                return HttpNotFound();
            }
            return View(availableTime);
        }

        // GET: AvailableTimes/Create
        public ActionResult Create()
        {
            if (User.IsInRole("General Practitioner") || User.IsInRole("Admin"))
            {
                var rm = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
                var gpRole = rm.FindByName("General Practitioner");
                var gpList = UserManager.Users
                    .Where(u => u.Roles.Any(r => r.RoleId == gpRole.Id))
                    .Select(u => new ProfileViewModel()
                    {
                        Id = u.Id,
                        FirstName = u.FirstName,
                        LastName = u.LastName,
                        Gender = u.Gender,
                        About = u.About,
                    }).ToList();
                ViewBag.SelectedGeneralPractitioner = new SelectList(gpList, "Id", "FirstName");
                return View();
            }
            return HttpNotFound();
        }

        // POST: AvailableTimes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GeneralPractioner,StartTime,EndTime")] AvailableTime availableTime, string SelectedGeneralPractitioner)
        {
            if (!User.IsInRole("Admin") && !User.IsInRole("General Practitioner")) return HttpNotFound();

            if (User.IsInRole("General Practitioner"))
            {
                availableTime.GeneralPractioner = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            }
            else if (User.IsInRole("Admin"))
            {
                availableTime.GeneralPractioner = db.Users.Where(u => u.Id == SelectedGeneralPractitioner).FirstOrDefault();
            }
            if (DateTime.Compare(availableTime.StartTime, availableTime.EndTime) >= 0)
            {
                ModelState.AddModelError("Time", "End time must larger than start time");
                var rm = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
                var gpRole = rm.FindByName("General Practitioner");
                var gpList = UserManager.Users
                    .Where(u => u.Roles.Any(r => r.RoleId == gpRole.Id))
                    .Select(u => new ProfileViewModel()
                    {
                        Id = u.Id,
                        FirstName = u.FirstName,
                        LastName = u.LastName,
                        Gender = u.Gender,
                        About = u.About,
                    }).ToList();
                ViewBag.SelectedGeneralPractitioner = new SelectList(gpList, "Id", "FirstName");
                return View(availableTime);
            }
            db.AvailableTimes.Add(availableTime);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: AvailableTimes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.IsInRole("Patient")) return HttpNotFound();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AvailableTime availableTime = db.AvailableTimes.Include(at => at.GeneralPractioner).Where(at => at.GeneralPractioner.Id == id.ToString()).FirstOrDefault();
            if (User.IsInRole("General Practitioner"))
            {
                if (availableTime == null || User.Identity.GetUserId() != availableTime.GeneralPractioner.Id)
                {
                    return HttpNotFound();
                }
            }
            if (availableTime == null)
            {
                return HttpNotFound();
            }
            return View(availableTime);
        }

        // POST: AvailableTimes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StartTime,EndTime")] AvailableTime availableTime)
        {
            if (ModelState.IsValid)
            {
                db.Entry(availableTime).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(availableTime);
        }

        // GET: AvailableTimes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (User.IsInRole("Patient")) return HttpNotFound();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AvailableTime availableTime = db.AvailableTimes.Include(at => at.GeneralPractioner).Where(at => at.GeneralPractioner.Id == id.ToString()).FirstOrDefault();
            if (User.IsInRole("General Practitioner"))
            {
                if (availableTime == null || User.Identity.GetUserId() != availableTime.GeneralPractioner.Id)
                {
                    return HttpNotFound();
                }
            }
            if (availableTime == null)
            {
                return HttpNotFound();
            }
            return View(availableTime);
        }

        // POST: AvailableTimes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AvailableTime availableTime = db.AvailableTimes.Find(id);
            db.AvailableTimes.Remove(availableTime);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyHealthClinic/Controllers/GeneralPractitionersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using MyHealthClinic.Helpers;
using MyHealthClinic.Models;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MyHealthClinic.Controllers
{
    public class GeneralPractitionersController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationDbContext _context = new ApplicationDbContext();


        public GeneralPractitionersController() { }

        public GeneralPractitionersController(ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set { _userManager = value; }
        }

        // GET: GeneralPractitioners
        public ActionResult Index()
        {
            var rm = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_context));
            var gpRole = rm.FindByName("General Practitioner");
            var gpList = UserManager.Users
                .Where(u => u.Roles.Any(r => r.RoleId == gpRole.Id))
                .Select(u => new ProfileViewModel()
                {
                    Id = u.Id,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Gender = u.Gender,
                    About = u.About,
                }).ToList();
            return View(gpList);
        }

        // GET: GeneralPractitioners/Details/5
        public ActionResult Details(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = UserManager.FindById(id);
            if (user == null) return HttpNotFound();
            var gpDetails = IdentityHelpers.GetProfileByUser(user);
            return View(gpDetails);
        }

        //
        // GET: GeneralPractitioners/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = UserManager.FindById(id);
            if (user == null) return HttpNotFound();
            var gpDetails = IdentityHelpers.GetProfileByUser(user);
            return View(gpDetails);
        }

        //
        // POST: GeneralPractitioners/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(ProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(model.Id);
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Dob = model.Dob;
                user.Gender = model.Gender;
                user.About = model.About;

                var result = UserManager.Update(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("upate GP error", string.Join(",", result.Errors));
                    return View(model);
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //
        // GET: GeneralPractitioners/Create
        public ActionResult Create()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }
            return HttpNotFound();
        }

        //
        // POST: GeneralPractitioners/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateGpViewModel model)
        {
            if (!User.IsInRole("Admin")) return HttpNotFound();
            if (!ModelState.IsValid) return View(model);

            var user = new ApplicationUser
            {
                UserName = model.Email,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Gender = model.Gender,
                About = model.About
            };
            var result = await UserManager.CreateAsync(user, model.Password);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("create GP error", string.Join(",", result.Errors));
                return View(model);
            }
            UserManager.AddToRole(user.Id, "General Practitioner");
            return RedirectToAction("Index");
        }

    }
}

MyHealthClinic/Views/GeneralPractitioners/Create.cshtml
@model MyHealthClinic.Models.CreateGpViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create GP</h2>

<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gender, EnumHelper.GetSelectList(typeof(MyHealthClinic.Models.Gender)))
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Register" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyHealthClinic/Views/GeneralPractitioners/Details.cshtml
@model MyHealthClinic.Models.ProfileViewModel
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>General Practitioner Details</h2>

<hr />

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.About)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to list", "Index")
</p>
<p>
    @Html.ActionLink("Check available time", "Index", "AvailableTimes", new { @id = Model.Id }, new { })
</p>

MyHealthClinic/Views/GeneralPractitioners/Edit.cshtml
@model MyHealthClinic.Models.ProfileViewModel

@{
    ViewBag.Title = "Edit GP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit General Practitioner</h2>

<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gender, Model.GenderList)
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.About, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.About, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

    </div>
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyHealthClinic/Views/GeneralPractitioners/Index.cshtml
@model IEnumerable<MyHealthClinic.Models.ProfileViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Our General Practioners</h2>

@if (User.IsInRole("Admin"))
{
    <p>
        @Html.ActionLink("Create New GP", "Create")
    </p>
}

<table class="table" id="gpTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var gp in Model)
        {
            <tr>
                <th>
                    @Html.DisplayFor(modelItem => gp.FirstName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => gp.LastName)
                </th>
                <th>
                    @Html.DisplayFor(modelItem => gp.Gender)
                </th>
                <th>
                    @Html.ActionLink("Details", "Details", new { id = gp.Id }, new { @class = "btn btn-default" })
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = gp.Id }, new { @class = "btn btn-default" })
                    }
                </th>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatables")
    <script>
        $(document).ready(function () {
            $('#gpTable').DataTable();
        });
    </script>
}