MyHealthClinic/Models/AvailableTime.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MyHealthClinic.Models
{
    public class AvailableTime
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public ApplicationUser GeneralPractioner { get; set; }

        [Required]
        public DateTime StartTime { get; set; }

        [Required]
        public DateTime EndTime { get; set; }

        public bool IsBooked { get; set; } = false;
    }
}

MyHealthClinic/Controllers/AvailableTimesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using MyHealthClinic.Models;
using System.Web;
using Microsoft.AspNet.Identity.Owin;
using System;

namespace MyHealthClinic.Controllers
{
    public class AvailableTimesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set { _userManager = value; }
        }

        // GET: AvailableTimes/id?
        public ActionResult Index(string id)
        {
            var model = db.AvailableTimes
                .Where(at => DateTime.Compare(at.StartTime, DateTime.Now) > 0)
                .Include(at => at.GeneralPractioner)
                .ToList();
            if (id != null)
            {
                model = db.AvailableTimes
                    .Where(at => at.GeneralPractioner.Id == id)
                    .Where(at => DateTime.Compare(at.StartTime, DateTime.Now) > 0)
                    .Include(at => at.GeneralPractioner)
                    .ToList();
            }
            return View(model);
        }

        // GET: AvailableTimes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AvailableTime availableTime = db.AvailableTimes.Find(id);
            if (availableTime == null)
            {
                return HttpNotFound();
            }
            return View(availableTime);
        }

        // GET: AvailableTimes/Create
        public ActionResult Create()
        {
            if (User.IsInRole("General Practitioner") || User.IsInRole("Admin"))
            {
                var rm = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
                var gpRole = rm.FindByName("General Practitioner");
                var gpList = UserManager.Users
                    .Where(u => u.Roles.Any(r => r.RoleId == gpRole.Id))
                    .Select(u => new ProfileViewModel()
                    {
                        Id = u.Id,
                        FirstName = u.FirstName,
                        LastName = u.LastName,
                        Gender = u.Gender,
                        About = u.About,
                    }).ToList();
                ViewBag.SelectedGeneralPractitioner = new SelectList(gpList, "Id", "FirstName");
                return View();
            }
            return HttpNotFound();
        }

        // POST: AvailableTimes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GeneralPractioner,StartTime,EndTime")] AvailableTime availableTime, string SelectedGeneralPractitioner)
        {
            if (!User.IsInRole("Admin") && !User.IsInRole("General Practitioner")) return HttpNotFound();

            if (User.IsInRole("General Practitioner"))
            {
                availableTime.GeneralPractioner = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            }
            else if (User.IsInRole("Admin"))
            {
                availableTime.GeneralPractioner = db.Users.Where(u => u.Id == SelectedGeneralPractitioner).FirstOrDefault();
            }
            if (DateTime.Compare(availableTime.StartTime, availableTime.EndTime) >= 0)
            {
                ModelState.AddModelError("Time", "End time must larger than start time");
                var rm = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
                var gpRole = rm.FindByName("General Practitioner");
                var gpList = UserManager.Users
                    .Where(u => u.Roles.Any(r => r.RoleId == gpRole.Id))
                    .Select(u => new ProfileViewModel()
                    {
                        Id = u.Id,
                        FirstName = u.FirstName,
                        LastName = u.LastName,
                        Gender = u.Gender,
                        About = u.About,
                    }).ToList();
                ViewBag.SelectedGeneralPractitioner = new SelectList(gpList, "Id", "FirstName");
                return View(availableTime);
            }
            db.AvailableTimes.Add(availableTime);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: AvailableTimes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.IsInRole("Patient")) return HttpNotFound();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AvailableTime availableTime = db.AvailableTimes.Include(at => at.GeneralPractioner).Where(at => at.GeneralPractioner.Id == id.ToString()).FirstOrDefault();
            if (User.IsInRole("General Practitioner"))
            {
                if (availableTime == null || User.Identity.GetUserId() != availableTime.GeneralPractioner.Id)
                {
                    return HttpNotFound();
                }
            }
            if (availableTime == null)
            {
                return HttpNotFound();
            }
            return View(availableTime);
        }

        // POST: AvailableTimes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StartTime,EndTime")] AvailableTime availableTime)
        {
            if (ModelState.IsValid)
            {
                db.Entry(availableTime).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(availableTime);
        }

        // GET: AvailableTimes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (User.IsInRole("Patient")) return HttpNotFound();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AvailableTime availableTime = db.AvailableTimes.Include(at => at.GeneralPractioner).Where(at => at.GeneralPractioner.Id == id.ToString()).FirstOrDefault();
            if (User.IsInRole("General Practitioner"))
            {
                if (availableTime == null || User.Identity.GetUserId() != availableTime.GeneralPractioner.Id)
                {
                    return HttpNotFound();
                }
            }
            if (availableTime == null)
            {
                return HttpNotFound();
            }
            return View(availableTime);
        }

        // POST: AvailableTimes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AvailableTime availableTime = db.AvailableTimes.Find(id);
            db.AvailableTimes.Remove(availableTime);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyHealthClinic/Controllers/ConsultsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyHealthClinic.Models;

namespace MyHealthClinic.Controllers
{
    public class ConsultsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Consults
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                return View(db.Consults.ToList());
            }
            return HttpNotFound();
        }

        // GET:MyConsults/id
        public ActionResult MyConsults()
        {
            var userId = User.Identity.GetUserId();
            if (User.IsInRole("Patient"))
            {
                var model = db.Consults
                    .Where(c => c.Patient.Id == userId)
                    .Include(c => c.AvailableTime)
                    .Include("AvailableTime.GeneralPractioner")
                    .ToList();
                return View(model);
            }
            else if (User.IsInRole("General Practitioner"))
            {
                var model = db.Consults
                   .Where(c => c.AvailableTime.GeneralPractioner.Id == userId)
                   .Include(c => c.AvailableTime)
                   .Include(c => c.Patient)
                   .ToList();
                return View(model);
            }
            return HttpNotFound();
        }

        // GET: Create/id
        public ActionResult Create(int? id)
        {
            if (!User.IsInRole("Patient")) return HttpNotFound();
            if (id == null) return HttpNotFound();
            var availableTime = db.AvailableTimes.Find(id);
            if (availableTime == null) return HttpNotFound();
            availableTime.IsBooked = true;
            var userId = User.Identity.GetUserId();
            var patient = db.Users.Where(u => u.Id == userId).FirstOrDefault();
            var consult = new Consult
            {
                AvailableTime = availableTime,
                Patient = patient
            };
            db.Consults.Add(consult);
            db.Entry(availableTime).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("MyConsults");
        }

        // GET: Consults/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consult consult = db.Consults
                .Where(c => c.Id == id)
                .Include(c => c.Patient)
                .Include(c => c.AvailableTime)
                .Include(c => c.AvailableTime.GeneralPractioner)
                .FirstOrDefault();
            if (consult == null)
            {
                return HttpNotFound();
            }
            var userId = User.Identity.GetUserId();
            if ((User.IsInRole("Patient") && userId != consult.Patient.Id) || (User.IsInRole("General Practitioner") && userId != consult.AvailableTime.GeneralPractioner.Id))
            {
                return HttpNotFound();
            }
            return View(consult);
        }

        // POST: Consults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consult consult = db.Consults
                .Where(c => c.Id == id)
                .Include(c => c.AvailableTime)
                .FirstOrDefault();
            var availableTime = consult.AvailableTime;
            availableTime.IsBooked = false;
            db.Consults.Remove(consult);
            db.Entry(availableTime).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("MyConsults");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyHealthClinic/Views/AvailableTimes/Create.cshtml
@model MyHealthClinic.Models.AvailableTime

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AvailableTime</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control datetimepicker" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (User.IsInRole("Admin"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.GeneralPractioner, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SelectedGeneralPractitioner", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GeneralPractioner.Id, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datetimepicker")
    <script>
        $(function () {
            $('.datetimepicker').datetimepicker({
                format: "MMM/DD/YYYY HH:mm",
                minDate: new Date()
            });
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "MMM/DD/YYYY HH:mm", true).isValid();
            }
        });
    </script>

}

MyHealthClinic/Views/AvailableTimes/Delete.cshtml
@model MyHealthClinic.Models.AvailableTime

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AvailableTime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyHealthClinic/Views/AvailableTimes/Details.cshtml
@model MyHealthClinic.Models.AvailableTime

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AvailableTime</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyHealthClinic/Views/AvailableTimes/Edit.cshtml
@model MyHealthClinic.Models.AvailableTime

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AvailableTime</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyHealthClinic/Views/AvailableTimes/Index.cshtml
@model IEnumerable<MyHealthClinic.Models.AvailableTime>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GP Available Time</h2>
@if (User.IsInRole("Admin") || User.IsInRole("General Practitioner"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table" id="available-time-table">
    <thead>
        <tr>
            <th>
                General Practitioner
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsBooked)
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.GeneralPractioner.FirstName)
                    @Html.DisplayFor(modelItem => item.GeneralPractioner.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsBooked)
                </td>
                <td>

                    @if (User.IsInRole("Admin") || User.IsInRole("General Practitioner"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-default" })
                    }
                    else if (item.IsBooked)
                    {
                        @Html.ActionLink("Book", "Edit", new { id = item.Id }, new { @class = "btn btn-default disabled" })
                    }
                    else
                    {
                        @Html.ActionLink("Book", "Create", "Consults", new { id = item.Id }, new { @class = "btn btn-primary" })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatables")
    <script>
        $(document).ready(function () {
            $('#available-time-table').DataTable();
        });
    </script>
}