MyHealthClinic/Controllers/GeneralPractitionersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using MyHealthClinic.Helpers;
using MyHealthClinic.Models;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MyHealthClinic.Controllers
{
    public class GeneralPractitionersController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationDbContext _context = new ApplicationDbContext();


        public GeneralPractitionersController() { }

        public GeneralPractitionersController(ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set { _userManager = value; }
        }

        // GET: GeneralPractitioners
        public ActionResult Index()
        {
            var rm = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_context));
            var gpRole = rm.FindByName("General Practitioner");
            var gpList = UserManager.Users
                .Where(u => u.Roles.Any(r => r.RoleId == gpRole.Id))
                .Select(u => new ProfileViewModel()
                {
                    Id = u.Id,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Gender = u.Gender,
                    About = u.About,
                }).ToList();
            return View(gpList);
        }

        // GET: GeneralPractitioners/Details/5
        public ActionResult Details(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = UserManager.FindById(id);
            if (user == null) return HttpNotFound();
            var gpDetails = IdentityHelpers.GetProfileByUser(user);
            return View(gpDetails);
        }

        //
        // GET: GeneralPractitioners/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var user = UserManager.FindById(id);
            if (user == null) return HttpNotFound();
            var gpDetails = IdentityHelpers.GetProfileByUser(user);
            return View(gpDetails);
        }

        //
        // POST: GeneralPractitioners/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(ProfileViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(model.Id);
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Dob = model.Dob;
                user.Gender = model.Gender;
                user.About = model.About;

                var result = UserManager.Update(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("upate GP error", string.Join(",", result.Errors));
                    return View(model);
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //
        // GET: GeneralPractitioners/Create
        public ActionResult Create()
        {
            if (User.IsInRole("Admin"))
            {
                return View();
            }
            return HttpNotFound();
        }

        //
        // POST: GeneralPractitioners/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateGpViewModel model)
        {
            if (!User.IsInRole("Admin")) return HttpNotFound();
            if (!ModelState.IsValid) return View(model);

            var user = new ApplicationUser
            {
                UserName = model.Email,
                Email = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Gender = model.Gender,
                About = model.About
            };
            var result = await UserManager.CreateAsync(user, model.Password);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("create GP error", string.Join(",", result.Errors));
                return View(model);
            }
            UserManager.AddToRole(user.Id, "General Practitioner");
            return RedirectToAction("Index");
        }

    }
}

MyHealthClinic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyHealthClinic.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyHealthClinic/Views/Home/About.cshtml
@{
    ViewBag.Title = "Booking info";
}
<h2>Booking info</h2>


<p>Use this area to provide additional information.</p>

MyHealthClinic/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contact us</h2>

<address>
    246 Clayton Rd,<br />
    Clayton, VIC 3168<br />
    <abbr title="Phone">P:</abbr>
    +61 (0) 412 345 678
</address>

<hr />

<div id="container">
    <div id="map"></div>
    <div id="sidebar"></div>
</div>
<div style="margin:10px;">
    <h3>Get your way</h3>
    <div class="row" style="margin:10px;">
        <label for="start" class="col-md-2 control-label">Start</label>
        <input type="text" id="start" class="col-md-4 form-control" />
        <label for="end" class="col-md-2 control-label">End</label>
        <select id="end" class="col-md-4 form-control">
            <option value="246 Clayton Rd, Clayton VIC 3168">246 Clayton Rd, Clayton VIC 3168</option>
        </select>
    </div>

    <div class="row" style="margin:10px;">
        <label for="mode" class="col-md-2 control-label">Travel mode</label>
        <select id="mode" class="col-md-4 form-control">
            <option value="DRIVING">Driving</option>
            <option value="WALKING">Walking</option>
            <option value="BICYCLING">Bicycling</option>
            <option value="TRANSIT">Transit</option>
        </select>
        <input type="submit" value="Go" class="btn btn-default col-md-offset-2 col-md-2" id="get-direction" />
    </div>
</div>

@section Scripts {
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    @Scripts.Render("~/bundles/map")
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCpCwxOn9dVTg5P_r1vNmvUuKgD405ktDE&callback=initMap&libraries=places&v=weekly" async></script>
}

MyHealthClinic/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<section>
    <div class="home-background">
        <picture>
            <source media="(min-width: 1080px)" srcset="/Content/Images/home_background_1080.jpg">
            <source media="(min-width: 720px)" srcset="/Content/Images/home_background_720.jpg">
            <source media="(min-width: 400px)" srcset="/Content/Images/home_background_400.jpg">
            <img src="/Content/Images/home_background_400.jpg" alt="imagealttext" class="home-background">
        </picture>
    </div>
</section>


<div class="row">
    <div class="col-md-4">
        <h2>Our GP</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque magna risus,
            posuere sit amet magna pellentesque, semper maximus ex. Phasellus ut dolor ipsum.
            Sed pretium lacus metus, a accumsan risus egestas a.
            Morbi aliquam gravida dolor id scelerisque. Duis sed luctus lectus.
        </p>
        <p>
            @Html.ActionLink("Find GP", "Index", "GeneralPractitioners", new { }, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2>Booking Info</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque magna risus,
            posuere sit amet magna pellentesque, semper maximus ex. Phasellus ut dolor ipsum.
            Sed pretium lacus metus, a accumsan risus egestas a.
            Morbi aliquam gravida dolor id scelerisque. Duis sed luctus lectus.
        </p>
        <p>
            @Html.ActionLink("Learn More", "About", new { }, new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="col-md-4">
        <h2>Find Us</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque magna risus,
            posuere sit amet magna pellentesque, semper maximus ex. Phasellus ut dolor ipsum.
            Sed pretium lacus metus, a accumsan risus egestas a.
            Morbi aliquam gravida dolor id scelerisque. Duis sed luctus lectus.
        </p>
        <p>
            @Html.ActionLink("Get Direction", "Contact", new { }, new { @class = "btn btn-default" })
        </p>
    </div>
</div>